In [4]:
# Импорт библиотеки NumPy
import numpy as np

In [21]:
# Примеры создания массивов
# Массив из списков:
a = np.array([12, 7, 23, 5, 11])
# Массивы, созданные с помощью функций zeroes(), ones() и arrange():
zero = np.zeros((6,2))
one = np.ones((3,3))
Ar = np.arange(16, 32, 2)
# Создание двумерного массива из списков:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [22]:
# Вывод формы и типа данных для массива b.
print("b: ", b)
print("Shape b: ", b.shape)
print("Type b: ", b.dtype)
print("Ndim b: ", b.ndim)

b:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape b:  (3, 3)
Type b:  int64
Ndim b:  2


In [23]:
# Примеры индексирования и срезов.
# получение отдельного элемента.
print(b[1,1])
# извлечение подмассива с помощью среза.
print(b[1])

5
[4 5 6]


In [24]:
# Примеры векторных операций и базовых статистик
# поэлементное сложение массивов.
print(one + b)
# поэлементное умножение массивов.
print(b*b)
# вычисление средней величины массива a.
print("Массив a: ", a)
print("Средняя величина a: ", a.mean())
min_a = a.min()
max_a = a.max()
norm_a = (a - min_a) / (max_a - min_a)
print("Нормированная средняя величина a: ", norm_a)

[[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
Массив a:  [12  7 23  5 11]
Средняя величина a:  11.6
Нормированная средняя величина a:  [0.38888889 0.11111111 1.         0.         0.33333333]
